Repository tendermint/liquidity, pull requests merged in 2021-05, with the labels that each got.

#236 Fix withdraw issues
  x/liquidity/keeper/common_test.go
  x/liquidity/keeper/invariants.go
  x/liquidity/keeper/invariants_test.go
  x/liquidity/keeper/liquidity_pool.go
  x/liquidity/keeper/liquidity_pool_test.go
Labels: bug

#356 swagger.yaml edits for liquidity module
  client/docs/swagger-ui/swagger.yaml
Labels: documentation

#348 Update tests to table driven tests approach
  x/liquidity/types/genesis_test.go
  x/liquidity/types/liquidity_pool_test.go
  x/liquidity/types/msgs_test.go
  x/liquidity/types/utils_test.go
Labels: test and simulation

#362 Querying twice in some CLI command
  Makefile
  x/liquidity/client/cli/query.go
  x/liquidity/client/cli/tx.go
Labels: client

#371 Do not call GetAccount for address in the MsgCreatePool
  x/liquidity/keeper/liquidity_pool.go
Labels: bug

#372 Calculate order expiry span height correctly
  x/liquidity/keeper/batch.go
  x/liquidity/keeper/batch_test.go
  x/liquidity/keeper/liquidity_pool.go
  x/liquidity/keeper/msg_server.go
  x/liquidity/types/swap.go
Labels: bug
