Repository tendermint/liquidity, pull requests merged in 2021-06, with the labels that each got.

#373 update genesis.proto
  proto/tendermint/liquidity/v1beta1/genesis.proto
  x/liquidity/types/genesis.pb.go
Labels: documentation

#374 Update liquidity.proto
  client/docs/statik/statik.go
  client/docs/swagger-ui/swagger.yaml
  proto/tendermint/liquidity/v1beta1/liquidity.proto
  x/liquidity/types/liquidity.pb.go
Labels: documentation

#387 Add DEX Circuit Breaker 2
  client/docs/statik/statik.go
  client/docs/swagger-ui/swagger.yaml
  proto/tendermint/liquidity/v1beta1/liquidity.proto
  x/liquidity/client/cli/cli_test.go
  x/liquidity/keeper/keeper.go
  x/liquidity/keeper/keeper_test.go
  x/liquidity/keeper/msg_server.go
  x/liquidity/spec/08_params.md
  x/liquidity/types/errors.go
  x/liquidity/types/liquidity.pb.go
  x/liquidity/types/params.go
  x/liquidity/types/params_internal_test.go
  x/liquidity/types/params_test.go
Labels: enhancement

#369 Change the logic to determine if the pool was depleted
  x/liquidity/keeper/liquidity_pool.go
  x/liquidity/keeper/liquidity_pool_test.go
  x/liquidity/keeper/swap.go
  x/liquidity/keeper/swap_test.go
Labels: bug

#386 Decrease error rate threshold and merge invariant checks
  x/liquidity/keeper/invariants.go
  x/liquidity/keeper/invariants_test.go
  x/liquidity/keeper/liquidity_pool.go
Labels: test and simulation

#388 Separate balance check for reserve coins in pool creation
  x/liquidity/keeper/batch_test.go
  x/liquidity/keeper/liquidity_pool.go
  x/liquidity/keeper/liquidity_pool_test.go
  x/liquidity/types/errors.go
Labels: enhancement

#391 Fix empty request check
  x/liquidity/keeper/grpc_query.go
Labels: bug

#397 update cosmos-sdk version to 0.42.5
  go.mod
  go.sum
Labels: migration

#376 Add linter
  .github/workflows/lint.yml
  .golangci.yml
  app/test_helpers.go
  client/docs/statik/init.go
  cmd/liquidityd/cmd/testnet.go
  x/liquidity/client/cli/cli_test.go
  x/liquidity/client/cli/query.go
  x/liquidity/client/cli/tx.go
  x/liquidity/client/testutil/cli_helpers.go
  x/liquidity/doc.go
  x/liquidity/genesis_test.go
  x/liquidity/handler_test.go
  x/liquidity/keeper/batch_test.go
  x/liquidity/keeper/common_test.go
  x/liquidity/keeper/genesis_test.go
  x/liquidity/keeper/invariants.go
  x/liquidity/keeper/invariants_test.go
  x/liquidity/keeper/liquidity_pool.go
  x/liquidity/keeper/liquidity_pool_test.go
  x/liquidity/keeper/msg_server_test.go
  x/liquidity/keeper/querier_test.go
  x/liquidity/keeper/store.go
  x/liquidity/keeper/store_test.go
  x/liquidity/keeper/swap.go
  x/liquidity/keeper/swap_test.go
  x/liquidity/module.go
  x/liquidity/simulation/operations.go
  x/liquidity/simulation/operations_test.go
  x/liquidity/types/errors.go
  x/liquidity/types/keys.go
  x/liquidity/types/liquidity_pool.go
  x/liquidity/types/liquidity_pool_test.go
  x/liquidity/types/msgs.go
  x/liquidity/types/msgs_test.go
  x/liquidity/types/params.go
  x/liquidity/types/querier.go
  x/liquidity/types/swap.go
  x/liquidity/types/swap_test.go
  x/liquidity/types/utils.go
  x/liquidity/types/utils_test.go
Labels: devops

#390 Add query a pool endpoint through poolCoin or reserveAcc
  README.md
  client/docs/config.json
  client/docs/statik/statik.go
  client/docs/swagger-ui/swagger.yaml
  doc/client.md
  go.mod
  proto/tendermint/liquidity/v1beta1/query.proto
  x/liquidity/client/cli/cli_test.go
  x/liquidity/client/cli/flags.go
  x/liquidity/client/cli/query.go
  x/liquidity/keeper/grpc_query.go
  x/liquidity/keeper/grpc_query_test.go
  x/liquidity/keeper/liquidity_pool.go
  x/liquidity/keeper/querier_test.go
  x/liquidity/types/query.pb.go
  x/liquidity/types/query.pb.gw.go
  x/liquidity/types/utils.go
  x/liquidity/types/utils_test.go
Labels: enhancement

#402 Improve docs: liquidity.proto, query.proto, tx.proto, batch.go and a few other files
  client/docs/statik/statik.go
  client/docs/swagger-ui/swagger.yaml
  proto/tendermint/liquidity/v1beta1/liquidity.proto
  proto/tendermint/liquidity/v1beta1/query.proto
  proto/tendermint/liquidity/v1beta1/tx.proto
  x/liquidity/keeper/batch.go
  x/liquidity/types/liquidity.pb.go
  x/liquidity/types/query.pb.go
  x/liquidity/types/tx.pb.go
Labels: documentation

#406 Fix module specific logger
  x/liquidity/keeper/liquidity_pool.go
Labels: enhancement

#378 docs: Improve liquidity module spec for concepts, state, README
  x/liquidity/spec/01_concepts.md
  x/liquidity/spec/02_state.md
  x/liquidity/spec/README.md
Labels: documentation

#350 Fix simulation test
  Makefile
  app/params/weights.go
  app/sim_test.go
  x/liquidity/simulation/genesis.go
  x/liquidity/simulation/operations.go
  x/liquidity/simulation/operations_test.go
  x/liquidity/simulation/operations_utils.go
Labels: bug, test and simulation

#417 Fix add genesis account cli command
  cmd/liquidityd/cmd/genaccounts.go
Labels: bug, client

#408 Update README.md file
  README.md
Labels: documentation

#409 Add Contributing Guidelines
  CONTRIBUTING.md
Labels: documentation

#410 refactoring and disable onchain batch invariant checking logics
  app/test_helpers.go
  x/liquidity/keeper/genesis.go
  x/liquidity/keeper/invariants.go
  x/liquidity/keeper/liquidity_pool.go
  x/liquidity/keeper/msg_server.go
  x/liquidity/keeper/swap.go
  x/liquidity/keeper/swap_test.go
  x/liquidity/spec/07_events.md
  x/liquidity/types/events.go
  x/liquidity/types/params.go
  x/liquidity/types/swap.go
  x/liquidity/types/swap_test.go
Labels: enhancement

#429 Add Security Audit Report on doc
  README.md
  doc/Least_Authority_Liquidity_Module_Security_Audit_Report.pdf
  x/liquidity/spec/08_params.md
Labels: documentation
